// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SugarGuard.API.Data;

#nullable disable

namespace SugarGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203180141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GlucoseValueAtRequest")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value_at_request");

                    b.Property<bool>("IsFromCache")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_cache");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_used");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation_text");

                    b.Property<string>("Urgency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("urgency");

                    b.HasKey("RecommendationId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("idx_recommendations_child");

                    b.ToTable("ai_recommendations");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChildId");

                    b.ToTable("backpack_history");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("backpack_item_id");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("added_by");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("BackpackItemId");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("idx_backpack_child");

                    b.ToTable("backpack_items");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentInsulins")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_insulins");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DiabetesType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("diabetes_type");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("diagnosis_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<string>("InsulinScheme")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("insulin_scheme");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("ChildId");

                    b.ToTable("children");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.Property<Guid>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("code_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.HasKey("CodeId");

                    b.HasIndex("ChildId");

                    b.ToTable("connection_codes");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<decimal>("CarbInsulinRatio")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("carb_insulin_ratio");

                    b.Property<decimal>("InsulinSensitivity")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("insulin_sensitivity");

                    b.Property<decimal>("TargetRangeMax")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_max");

                    b.Property<decimal>("TargetRangeMin")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_min");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ChildId");

                    b.ToTable("diabetes_settings");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("ChildState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("child_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<decimal>("GlucoseValue")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.HasKey("MeasurementId");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.HasIndex("ChildId", "MeasurementTime")
                        .HasDatabaseName("idx_measurements_child_time");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChildId", "ScheduledTime")
                        .IsUnique()
                        .HasDatabaseName("idx_schedules_child");

                    b.ToTable("measurement_schedules");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentUserId", "ChildId")
                        .IsUnique();

                    b.ToTable("parent_child_links");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("LogId");

                    b.HasIndex("ChildId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("snack_consumption_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EncryptedEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_email");

                    b.Property<string>("EncryptedFirstName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_first_name");

                    b.Property<string>("EncryptedLastName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_salt");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("UserId");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasFilter("telegram_id IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.Navigation("Child");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackHistory")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackItems")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ConnectionCodes")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithOne("DiabetesSettings")
                        .HasForeignKey("SugarGuard.Domain.Entities.DiabetesSettings", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("Measurements")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithOne()
                        .HasForeignKey("SugarGuard.Domain.Entities.Measurement", "RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("MeasurementSchedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "ParentUser")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("SnackConsumptionLogs")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("BackpackHistory");

                    b.Navigation("BackpackItems");

                    b.Navigation("ConnectionCodes");

                    b.Navigation("DiabetesSettings");

                    b.Navigation("MeasurementSchedules");

                    b.Navigation("Measurements");

                    b.Navigation("ParentChildLinks");

                    b.Navigation("SnackConsumptionLogs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("ParentChildLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
