// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SugarGuard.API.Data;

#nullable disable

namespace SugarGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204000000_AddBotUserContextsTable")]
    partial class AddBotUserContextsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // Модель будет автоматически сгенерирована EF Core
#pragma warning restore 612, 618
        }
    }
}
