// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SugarGuard.API.Data;

#nullable disable

namespace SugarGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720165455_AddUserMapProvider")]
    partial class AddUserMapProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GlucoseValueAtRequest")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value_at_request");

                    b.Property<bool>("IsFromCache")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_cache");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_used");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation_text");

                    b.Property<string>("Urgency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("urgency");

                    b.HasKey("RecommendationId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("idx_recommendations_child");

                    b.ToTable("ai_recommendations");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiContextSnapshot", b =>
                {
                    b.Property<Guid>("ContextSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("context_snapshot_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("format_version");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.HasKey("ContextSnapshotId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_ai_context_snapshots_child_created");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_ai_context_snapshots_conversation_created");

                    b.ToTable("ai_context_snapshots");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("ProviderConversationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_conversation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("SummaryUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_updated_at");

                    b.HasKey("ConversationId");

                    b.HasIndex("ChildId", "Status", "LastMessageAt")
                        .HasDatabaseName("ix_ai_conversations_child_status_last");

                    b.ToTable("ai_conversations");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiConversationMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("role");

                    b.Property<string>("SafetyResult")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("safety_result");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("MessageId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("RecommendationId")
                        .HasDatabaseName("ix_ai_messages_recommendation");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_ai_messages_conversation_created");

                    b.ToTable("ai_conversation_messages");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.HasKey("AuditLogId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChildId");

                    b.ToTable("backpack_history");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("backpack_item_id");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("added_by");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("BackpackItemId");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("idx_backpack_child");

                    b.ToTable("backpack_items");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BotUserContext", b =>
                {
                    b.Property<Guid>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_child_id");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("ContextId");

                    b.HasIndex("CurrentChildId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_botcontext_telegram");

                    b.ToTable("bot_user_contexts");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentInsulins")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_insulins");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DiabetesType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("diabetes_type");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("diagnosis_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<string>("InsulinScheme")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("insulin_scheme");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<bool>("SetupCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("setupcompleted");

                    b.Property<DateTime?>("SetupCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("setupcompletedat");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("ChildId");

                    b.ToTable("children");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ChildAchievement", b =>
                {
                    b.Property<Guid>("ChildAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("child_achievement_id");

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("achievement_code");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.HasKey("ChildAchievementId");

                    b.HasIndex("ChildId", "AchievementCode")
                        .IsUnique()
                        .HasDatabaseName("ux_child_achievements_child_code");

                    b.ToTable("child_achievements");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.Property<Guid>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("code_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.HasKey("CodeId");

                    b.HasIndex("ChildId");

                    b.ToTable("connection_codes");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<decimal>("CarbInsulinRatio")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("carb_insulin_ratio");

                    b.Property<decimal>("InsulinSensitivity")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("insulin_sensitivity");

                    b.Property<decimal>("TargetRangeMax")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_max");

                    b.Property<decimal>("TargetRangeMin")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_min");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ChildId");

                    b.ToTable("diabetes_settings");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorChildLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivatedat");

                    b.Property<Guid>("DoctorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid?>("LinkedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedbyuserid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.HasKey("LinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("DoctorUserId", "ChildId")
                        .IsUnique();

                    b.ToTable("doctor_child_links");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorNote", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("noteid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("childid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DoctorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctoruserid");

                    b.Property<bool>("IsImportant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isimportant");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurementid");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notetext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("NoteId");

                    b.HasIndex("MeasurementId")
                        .HasDatabaseName("IXdoctornotesmeasurementid")
                        .HasFilter("measurementid IS NOT NULL");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("IXdoctornoteschildidcreatedat");

                    b.HasIndex("DoctorUserId", "ChildId")
                        .HasDatabaseName("IXdoctornotesdoctoruseridchildid");

                    b.ToTable("doctornotes");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ExportJob", b =>
                {
                    b.Property<Guid>("ExportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_job_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("download_url");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_from");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_to");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ExportJobId");

                    b.ToTable("export_jobs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.FaqArticle", b =>
                {
                    b.Property<Guid>("FaqArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("faq_article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("FaqArticleId");

                    b.ToTable("faq_articles");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.InviteCode", b =>
                {
                    b.Property<Guid>("InviteCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invitecodeid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("childid");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimedbydyuserid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("targetrole");

                    b.HasKey("InviteCodeId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invitecodes_code");

                    b.HasIndex("ChildId", "ExpiresAt")
                        .HasDatabaseName("ix_invitecodes_child_expires");

                    b.ToTable("invitationcodes");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MealSchedule", b =>
                {
                    b.Property<Guid>("MealScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("meal_schedule_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week_mask");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("meal_type");

                    b.Property<decimal?>("PlannedBreadUnits")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("planned_bread_units");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_enabled");

                    b.Property<int>("ReminderMinutesBefore")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_minutes_before");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MealScheduleId");

                    b.HasIndex("ChildId", "ScheduledTime", "Title")
                        .IsUnique()
                        .HasDatabaseName("ux_meal_schedules_child_time_title");

                    b.ToTable("meal_schedules");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("ChildState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("child_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<string>("GlucoseUiState")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("glucose_ui_state")
                        .HasComputedColumnSql("CASE WHEN glucose_value <= 3.1 OR glucose_value > 15.0 THEN 'Critical' WHEN glucose_value >= 4.0 AND glucose_value <= 10.0 THEN 'Normal' ELSE 'Attention' END", true);

                    b.Property<decimal>("GlucoseValue")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.HasKey("MeasurementId");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.HasIndex("ChildId", "MeasurementTime")
                        .HasDatabaseName("idx_measurements_child_time");

                    b.HasIndex("ChildId", "GlucoseUiState", "MeasurementTime")
                        .HasDatabaseName("idx_measurements_child_uistate_time");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChildId", "ScheduledTime")
                        .IsUnique()
                        .HasDatabaseName("idx_schedule_child");

                    b.ToTable("measurement_schedules");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.NutritionEntry", b =>
                {
                    b.Property<Guid>("NutritionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("nutrition_entry_id");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("GlucoseBefore")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_before");

                    b.Property<decimal>("InsulinUnits")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("insulin_units");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("meal_name");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("meal_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("NutritionEntryId");

                    b.HasIndex("ChildId", "RecordedAt")
                        .HasDatabaseName("ix_nutrition_entries_child_recorded");

                    b.ToTable("nutrition_entries");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.OnboardingEvent", b =>
                {
                    b.Property<Guid>("OnboardingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("onboardingeventid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationOnSecond")
                        .HasColumnType("integer")
                        .HasColumnName("durationonsecond");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("eventtype");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RequestIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("requestip");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stepname");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("stepnumber");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("userrole");

                    b.HasKey("OnboardingEventId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idxonboardingeventscreatedat");

                    b.HasIndex("StepNumber", "EventType")
                        .HasDatabaseName("idxonboardingeventssteptype")
                        .HasFilter("eventtype IN ('started', 'completed')");

                    b.HasIndex("UserId", "StepNumber")
                        .HasDatabaseName("idxonboardingeventsuseridstep");

                    b.HasIndex("UserRole", "EventType")
                        .HasDatabaseName("idxonboardingeventsroletype");

                    b.ToTable("onboardingevents", (string)null);
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LinkedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linkedbyuserid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentUserId", "ChildId")
                        .IsUnique();

                    b.ToTable("parent_child_links");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("P256Dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("pushsubscriptions", (string)null);
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CreatedByUserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("LogId");

                    b.HasIndex("ChildId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("snack_consumption_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SupportConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CallbackEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("callback_email");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ConversationId");

                    b.HasIndex("RequesterUserId", "UpdatedAt")
                        .HasDatabaseName("ix_support_conversations_requester_updated");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_support_conversations_status_updated");

                    b.ToTable("support_conversations");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SupportMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("ReadByRequester")
                        .HasColumnType("boolean")
                        .HasColumnName("read_by_requester");

                    b.Property<bool>("ReadBySupport")
                        .HasColumnType("boolean")
                        .HasColumnName("read_by_support");

                    b.HasKey("MessageId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_support_messages_conversation_created");

                    b.ToTable("support_messages");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sync_log_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<bool>("IsConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("is_conflict");

                    b.Property<string>("ResolutionSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolution_source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("SyncLogId");

                    b.ToTable("sync_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivatedat");

                    b.Property<string>("DoctorSpecialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("doctor_specialty");

                    b.Property<string>("EmailForLogin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_for_login");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailverifiedat");

                    b.Property<string>("EncryptedDoctorLicense")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_doctor_license");

                    b.Property<string>("EncryptedEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_email");

                    b.Property<string>("EncryptedFirstName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_first_name");

                    b.Property<string>("EncryptedLastName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_last_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isemailverified");

                    b.Property<string>("MapProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("map_provider");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboardingcompleted");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboardingcompletedat");

                    b.Property<int>("OnboardingCurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboardingcurrentstep");

                    b.Property<DateTime?>("OnboardingSkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboardingskippedat");

                    b.Property<DateTime?>("OnboardingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboardingstartedat");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_salt");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Parent")
                        .HasColumnName("role");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("UserId");

                    b.HasIndex("EmailForLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_users_emailforlogin")
                        .HasFilter("\"emailforlogin\" IS NOT NULL");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasFilter("\"telegramid\" IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId");

                    b.HasIndex("ChildId");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_user_notifications_recipient_unread");

                    b.HasIndex("RecipientUserId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_notifications_recipient_source");

                    b.ToTable("user_notifications");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.Navigation("Child");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiContextSnapshot", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("AiContextSnapshots")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AiConversation", "Conversation")
                        .WithMany("ContextSnapshots")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("Conversation");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiConversation", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("AiConversations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiConversationMessage", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SugarGuard.Domain.Entities.AiConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuthorUser");

                    b.Navigation("Conversation");

                    b.Navigation("Measurement");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackHistory")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackItems")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BotUserContext", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "CurrentChild")
                        .WithMany()
                        .HasForeignKey("CurrentChildId");

                    b.Navigation("CurrentChild");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ChildAchievement", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("Achievements")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ConnectionCodes")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithOne("DiabetesSettings")
                        .HasForeignKey("SugarGuard.Domain.Entities.DiabetesSettings", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorChildLink", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("DoctorChildLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "DoctorUser")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("DoctorUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorNote", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "DoctorUser")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("DoctorUser");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.InviteCode", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId");

                    b.Navigation("Child");

                    b.Navigation("ClaimedByUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MealSchedule", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("MealSchedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("Measurements")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithOne()
                        .HasForeignKey("SugarGuard.Domain.Entities.Measurement", "RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("MeasurementSchedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.NutritionEntry", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("NutritionEntries")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.OnboardingEvent", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "ParentUser")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("SnackConsumptionLogs")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SupportConversation", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SupportMessage", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.SupportConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SugarGuard.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AiConversation", b =>
                {
                    b.Navigation("ContextSnapshots");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("Achievements");

                    b.Navigation("AiContextSnapshots");

                    b.Navigation("AiConversations");

                    b.Navigation("BackpackHistory");

                    b.Navigation("BackpackItems");

                    b.Navigation("ConnectionCodes");

                    b.Navigation("DiabetesSettings");

                    b.Navigation("DoctorChildLinks");

                    b.Navigation("MealSchedules");

                    b.Navigation("MeasurementSchedules");

                    b.Navigation("Measurements");

                    b.Navigation("NutritionEntries");

                    b.Navigation("ParentChildLinks");

                    b.Navigation("SnackConsumptionLogs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SupportConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("ParentChildLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
