// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SugarGuard.API.Data;

#nullable disable

namespace SugarGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426135432_AddRbacAdminSyncExportModules")]
    partial class AddRbacAdminSyncExportModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GlucoseValueAtRequest")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value_at_request");

                    b.Property<bool>("IsFromCache")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_cache");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_used");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation_text");

                    b.Property<string>("Urgency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("urgency");

                    b.HasKey("RecommendationId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("idx_recommendations_child");

                    b.ToTable("ai_recommendations");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.HasKey("AuditLogId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChildId");

                    b.ToTable("backpack_history");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.Property<Guid>("BackpackItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("backpack_item_id");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("added_by");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("BackpackItemId");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("idx_backpack_child");

                    b.ToTable("backpack_items");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BotUserContext", b =>
                {
                    b.Property<Guid>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_child_id");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("ContextId");

                    b.HasIndex("CurrentChildId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_bot_context_telegram");

                    b.ToTable("bot_user_contexts");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentInsulins")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_insulins");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DiabetesType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("diabetes_type");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("diagnosis_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<string>("InsulinScheme")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("insulin_scheme");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("ChildId");

                    b.ToTable("children");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.Property<Guid>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("code_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.HasKey("CodeId");

                    b.HasIndex("ChildId");

                    b.ToTable("connection_codes");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<decimal>("CarbInsulinRatio")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("carb_insulin_ratio");

                    b.Property<decimal>("InsulinSensitivity")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("insulin_sensitivity");

                    b.Property<decimal>("TargetRangeMax")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_max");

                    b.Property<decimal>("TargetRangeMin")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("target_range_min");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ChildId");

                    b.ToTable("diabetes_settings");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorChildLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("DoctorUserId", "ChildId")
                        .IsUnique();

                    b.ToTable("doctor_child_links");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ExportJob", b =>
                {
                    b.Property<Guid>("ExportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_job_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("download_url");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_from");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_to");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ExportJobId");

                    b.ToTable("export_jobs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.FaqArticle", b =>
                {
                    b.Property<Guid>("FaqArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("faq_article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("FaqArticleId");

                    b.ToTable("faq_articles");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("ChildState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("child_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<decimal>("GlucoseValue")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("glucose_value");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.HasKey("MeasurementId");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.HasIndex("ChildId", "MeasurementTime")
                        .HasDatabaseName("idx_measurements_child_time");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ChildId", "ScheduledTime")
                        .IsUnique()
                        .HasDatabaseName("idx_schedules_child");

                    b.ToTable("measurement_schedules");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentUserId", "ChildId")
                        .IsUnique();

                    b.ToTable("parent_child_links");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<decimal>("BreadUnits")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("bread_units");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("SnackName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snack_name");

                    b.HasKey("LogId");

                    b.HasIndex("ChildId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("snack_consumption_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sync_log_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<bool>("IsConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("is_conflict");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("SyncLogId");

                    b.ToTable("sync_logs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmailForLogin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_for_login");

                    b.Property<string>("EncryptedEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_email");

                    b.Property<string>("EncryptedFirstName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_first_name");

                    b.Property<string>("EncryptedLastName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Parent")
                        .HasColumnName("role");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("UserId");

                    b.HasIndex("EmailForLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_for_login")
                        .HasFilter("email_for_login IS NOT NULL");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasFilter("telegram_id IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.AIRecommendation", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.Navigation("Child");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackHistory", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackHistory")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BackpackItem", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("BackpackItems")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.BotUserContext", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "CurrentChild")
                        .WithMany()
                        .HasForeignKey("CurrentChildId");

                    b.Navigation("CurrentChild");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ConnectionCode", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ConnectionCodes")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DiabetesSettings", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithOne("DiabetesSettings")
                        .HasForeignKey("SugarGuard.Domain.Entities.DiabetesSettings", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.DoctorChildLink", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("DoctorChildLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "DoctorUser")
                        .WithMany()
                        .HasForeignKey("DoctorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("DoctorUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("Measurements")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithOne()
                        .HasForeignKey("SugarGuard.Domain.Entities.Measurement", "RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.MeasurementSchedule", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("MeasurementSchedules")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.ParentChildLink", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.User", "ParentUser")
                        .WithMany("ParentChildLinks")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.SnackConsumptionLog", b =>
                {
                    b.HasOne("SugarGuard.Domain.Entities.Child", "Child")
                        .WithMany("SnackConsumptionLogs")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SugarGuard.Domain.Entities.AIRecommendation", "AIRecommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId");

                    b.Navigation("AIRecommendation");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.Child", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("BackpackHistory");

                    b.Navigation("BackpackItems");

                    b.Navigation("ConnectionCodes");

                    b.Navigation("DiabetesSettings");

                    b.Navigation("DoctorChildLinks");

                    b.Navigation("MeasurementSchedules");

                    b.Navigation("Measurements");

                    b.Navigation("ParentChildLinks");

                    b.Navigation("SnackConsumptionLogs");
                });

            modelBuilder.Entity("SugarGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("ParentChildLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
